title: Crossroads
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image: "https://crds-cms-uploads.imgix.net/content/images/cr-social-sharing-still-bg.jpg"

# Build settings
permalink: pretty
markdown: kramdown

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - _assets/stylesheets
  - _assets/javascripts

include:
  - _redirects

exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - _migrations
  - vendor
  - netlify.toml

contentful:
  series:
    limit: 2
  message:
    limit: 4
  exclude:
    - author
    - album
    - commentary
    - discussion
    - discussion_question
    - episode
    - featured_media
    - migrations
    - podcast
    - sign_off
    - song
    - topic
    - video

collections_dir: collections

collections:
  pages:
    filename: "{{ permalink }} index"
    output: true
    permalink: /:permalink/index.html
  locations:
    output: true
    permalink: /:slug
  series:
    filename: "{{ starts_at | date: '%Y-%m-%d' }}-{{ slug }}"
    output: false
    has_many:
      - videos
  messages:
    filename: "{{ published_at | date: '%Y-%m-%d' }}-{{ slug }}"
    output: false
  promos:
    filename: "{{ published_at | date: '%Y-%m-%d-%H:%M:%S' }}-{{ title | slugify }}-{{ slug }}"
    output: false
  discussions:
    output: false
  articles:
    output: true
    permalink: /:collection/:title
  topics:
    output: true
    permalink: /:collection/:title
  authors:
    output: true
    permalink: /:collection/:title
  podcasts:
    output: true
    permalink: /:collection/:title
  episodes:
    output: true
    permalink: /podcasts/:podcast_slug/:title
  albums:
    output: true
    permalink: /:collection/:title
  songs:
    output: true
    permalink: /:collection/:title
  videos:
    output: true
    permalink: /:collection/:title
  series:
    output: true
    permalink: /:collection/:title
  tags:
    output: false
  features:
    output: false
  discussions:
    output: false
  messages:
    output: true
    permalink: /series/:series_slug/:title

defaults:
  - scope:
      path: ""
      type: "locations"
    values:
      layout: location

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  js_compressor: uglifier
  sources:
  - _assets/stylesheets
  - _assets/javascripts

imgix_params:
  placeholder: "auto=format,compress&w=10"
  placeholder_card: "auto=format,compress&w=12&h=9&fit=crop"
  placeholder_square: "auto=format,compress&w=10&h=10&fit=crop"
  placeholder_sixteen_nine: "auto=format,compress&w=16&h=9&fit=crop"

image_sizes:
  media_object: "(min-width: 768px) 140px, (min-width: 0px) 100px"
  cards_6x: "(min-width: 992px) 165px, (min-width: 0px) 50vw"
  cards_4x: "(min-width: 992px) 212.5px, (min-width: 768px) 345px, (min-width: 0px) 100vw"
  cards_3x: "(min-width: 992px) 390px, (min-width: 0px) 100vw"
  cards_3x_centered_carousel: "(min-width: 1200px) 232.5px, (min-width: 992px) 191px, (min-width: 768px) 146px, (min-width: 0px) 270px"
  cards_2x: "(min-width: 768px) 345px, (min-width: 0px) 100vw"
  music_thumb: "(min-width: 768px) 360px, (min-width: 0px) 323px"
  podcast_thumb: "(min-width: 768px) 330px, (min-width: 480px) 200px, (min-width: 0px) 100vw"
  episode_thumb: "(min-width: 768px) 120px, (min-width: 0px) 80px"
  album_thumb: "96px"
  song_artwork: "(min-width: 992px) 360px, (min-width: 0px) 100vw"
  avatar: "80px"
  full_width: "100vw"
  half_width: "50vw"
  one_hundred: "100%"
  topic_feature_sub: "(min-width: 992px) 370px, (min-width: 0px) 100px"

typekit_url: https://use.typekit.net/ccb3vpa.css
