title: Crossroads Media
email: info@crossroads.net
description: No matter what your beliefs, you are welcome here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image: "https://crds-cms-uploads.imgix.net/content/images/cr-social-sharing-still-bg.jpg"

# Build settings
permalink: pretty
markdown: kramdown

assets:
  source_maps: true # false on JEKYLL_ENV=production
  destination: "/assets"
  compression: true
  sources:
  - _assets/stylesheets
  - _assets/javascripts

include:
  - _redirects

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - _migrations
  - vendor
  - netlify.toml

collections_dir: collections

collections:
  pages:
    output: true
    permalink: /:slug
  locations:
    output: true
    permalink: /:collection/:slug
  series:
    output: true
    permalink: /:collection/:slug
  messages:
    output: true
    # permalink: /series/:series_slug/:slug
    permalink: /:slug

contentful:
  content_types:
    pages:
      id: page
      body: body
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
          permalink: slug
          layout: layout
          show_header: show_header
          show_footer: show_footer
    locations:
      id: location
      body: description
      frontmatter:
        entry_mappings:
          name: name
          slug: slug
          address: address
          service_times: service_times
          additional_info: additional_info
          image: image/url
          bg_image: bg_image/url
          map_url: map_url
        other:
          layout: location
          draft: false
    series:
      id: series
      body: description
      associations:
        videos:
          - messages
      frontmatter:
        entry_mappings:
          title: title
          slug: slug
          image: image/url
          bg_image: background_image/url
          start_date: starts_at
          end_date: ends_at
          youtube_url: youtube_url
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          year: "{{ starts_at | date: '%Y' }}"
          videos: videos/id
        other:
          layout: series
          draft: false
    messages:
      id: message
      body: description
      links:
        series_slug:
          content_type: series
          field: videos
          value: slug
      frontmatter:
        entry_mappings:
          title: title
          authors: author/full_name
          image: image/url
          source_url: source_url
          program: program/url
          video_duration: video_duration
          topic: category/title
          topic_slug: category/slug
          tags: tags
          transcription: transcription
          apple_podcasts_url: apple_podcasts_url
          google_play_url: google_play_url
          date: published_at
          slug: slug
        other:
          layout: video
          draft: false
