# default build settings for int, preview deploys etc
[build]
  command = '''
    bundle exec rspec &&
    ./bin/netlify-redirector &&
    bundle exec jekyll crds &&
    bundle exec jekyll contentful -f &&
    bundle exec jekyll build -- --cloudsearch
  '''
