# default build settings for int, preview deploys etc
[build]
  command = '''
    bundle exec rspec &&
    ruby lib/bin/redirects.rb &&
    bundle exec jekyll crds &&
    bundle exec jekyll contentful &&
    bundle exec jekyll build -- --cloudsearch
  '''
