[build]
  command = '''
    export CONTENTFUL_ACCESS_TOKEN=CONTENTFUL_ACCESS_TOKEN_$BRANCH &&
    export CONTENTFUL_MANAGEMENT_TOKEN=CONTENTFUL_MANAGEMENT_TOKEN_$BRANCH &&
    export STREAMSPOT_API_KEY=STREAMSPOT_API_KEY_$BRANCH &&
    bundle exec rspec &&
    ruby lib/bin/redirects.rb &&
    bundle exec jekyll crds &&
    bundle exec jekyll contentful --collections pages,promos,locations,series,messages
    bundle exec jekyll build
  '''
  
[context.int.environment]
  CONTENTFUL_ENV = "master"
  CONTENTFUL_SPACE_ID = "p9oq1ve41d7r"
  CRDS_APP_CLIENT_ENDPOINT = "https://int.static.crossroads.net"
  CRDS_CMS_ENDPOINT = "https://contentint.crossroads.net"
  CRDS_MAESTRO_CLIENT_ENDPOINT = "https://int.crossroads.net"
  IMGIX_DOMAIN = "crds-media-int.imgix.net"
  IMGIX_SRC = "images.ctfassets.net/p9oq1ve41d7r"
  STREAMSPOT_ID = "crossr30e3"

[context.demo.environment]
  CONTENTFUL_ENV = "master"
  CONTENTFUL_SPACE_ID = "hcu01lso1fic"
  CRDS_APP_CLIENT_ENDPOINT = "https://demo.static.crossroads.net"
  CRDS_CMS_ENDPOINT = "https://contentdemo.crossroads.net"
  CRDS_MAESTRO_CLIENT_ENDPOINT = "https://demo.crossroads.net"
  IMGIX_DOMAIN = "crds-media-int.imgix.net"
  IMGIX_SRC = "images.ctfassets.net/p9oq1ve41d7r"
  STREAMSPOT_ID = "crossr30e3"

[context.deploy-preview.environment]
  CONTENTFUL_ENV = "master"
  CONTENTFUL_SPACE_ID = "p9oq1ve41d7r"
  CRDS_APP_CLIENT_ENDPOINT = "https://int.static.crossroads.net"
  CRDS_CMS_ENDPOINT = "https://contentint.crossroads.net"
  CRDS_MAESTRO_CLIENT_ENDPOINT = "https://int.crossroads.net"
  IMGIX_DOMAIN = "crds-media-int.imgix.net"
  IMGIX_SRC = "images.ctfassets.net/p9oq1ve41d7r"
  STREAMSPOT_ID = "crossr30e3"

[context.deploy-preview]
  command = '''
    export CONTENTFUL_ACCESS_TOKEN=CONTENTFUL_ACCESS_TOKEN_INT &&
    export CONTENTFUL_MANAGEMENT_TOKEN=CONTENTFUL_MANAGEMENT_TOKEN_INT &&
    export STREAMSPOT_API_KEY=STREAMSPOT_API_KEY_INT &&
    bundle exec rspec &&
    ruby lib/bin/redirects.rb &&
    bundle exec jekyll crds &&
    bundle exec jekyll contentful --collections pages,promos,locations,series,messages
    bundle exec jekyll build
  '''
