# default build settings for int, preview deploys etc
[build]
  command = '''
    bundle exec rspec &&
    ./bin/contentful-redirects &&
    ./bin/netlify-redirector &&
    bundle exec jekyll crds &&
    bundle exec jekyll contentful -f &&
    bundle exec jekyll build -- --update-search-index &&
    bash ./cypress/kickOffCypress.sh
  '''

[context.branch-deploy.environment]
  CRDS_PEOPLE_DOMAIN = "crdspeople.netlify.com"
  CRDS_MAP_DOMAIN = "crdsmap.netlify.com"
  CRDS_ANGULAR_ENDPOINT = "https://dev-crds-angular.crossroads.net"

[context.deploy-preview.environment]
  CRDS_PEOPLE_DOMAIN = "crdspeople.netlify.com"
  CRDS_MAP_DOMAIN = "crdsmap.netlify.com"
  CRDS_ANGULAR_ENDPOINT = "https://dev-crds-angular.crossroads.net"

[context.development.environment]
  CRDS_PEOPLE_DOMAIN = "crdspeople.netlify.com"
  CRDS_MAP_DOMAIN = "crdsmap.netlify.com"
  CRDS_ANGULAR_ENDPOINT = "https://dev-crds-angular.crossroads.net"

[context.master.environment]
  CRDS_PEOPLE_DOMAIN = "crds-people-prod.netlify.com"
  CRDS_MAP_DOMAIN = "crds-map-prod.netlify.com"
  CRDS_ANGULAR_ENDPOINT = "https://dev-crds-angular.crossroads.net"
