# default build settings for int, preview deploys etc
[build]
  command = '''
    bundle exec rspec &&
    ruby lib/bin/redirects.rb &&
    bundle exec jekyll crds &&
    bundle exec jekyll contentful -f &&
    bundle exec jekyll build -- --cloudsearch
  '''

[context.development]
  CRDS_PEOPLE_DOMAIN=crdspeople.netlify.com
  CRDS_MAP_DOMAIN=crdsmap.netlify.com

[context.release]
  CRDS_PEOPLE_DOMAIN=crds-people-prod.netlify.com
  CRDS_MAP_DOMAIN=crds-map-prod.netlify.com
  